<?xml version="1.0" encoding="utf-8"?><Database Name="ProjectCShaft" Class="ProjectCShaftDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=ProjectCShaft;User ID=sa" SettingsObjectName="ProjectCShaft.Properties.Settings" SettingsPropertyName="ProjectCShaftConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="idMenu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nameMenu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="unitMenu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="priceMenu" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="descriptionMenu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Menu_Order_Table" Member="Order_Tables" ThisKey="idMenu" OtherKey="idMenuOrder_Table" Type="Order_Table" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Bida" Member="Table_Bidas">
    <Type Name="Table_Bida">
      <Column Name="idTable" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nameTable" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="typeTable" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="priceTable" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="statusTable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Association Name="Table_Bida_OrderMenu" Member="OrderMenus" ThisKey="idTable" OtherKey="idTable" Type="OrderMenu" />
      <Association Name="Table_Bida_Order_Table" Member="Order_Tables" ThisKey="idTable" OtherKey="idTable" Type="Order_Table" />
    </Type>
  </Table>
  <Table Name="dbo.OrderMenu" Member="OrderMenus">
    <Type Name="OrderMenu">
      <Column Name="idOrderMenu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idTable" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="nameMenuOrder" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="unitMenuOrder" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="priceMenuOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sumPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Table_Bida_OrderMenu" Member="Table_Bida" ThisKey="idTable" OtherKey="idTable" Type="Table_Bida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Table" Member="Order_Tables">
    <Type Name="Order_Table">
      <Column Name="idOrder" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idTable" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="idMenuOrder_Table" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="timeStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sumPriceTable" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Menu_Order_Table" Member="Menu" ThisKey="idMenuOrder_Table" OtherKey="idMenu" Type="Menu" IsForeignKey="true" />
      <Association Name="Table_Bida_Order_Table" Member="Table_Bida" ThisKey="idTable" OtherKey="idTable" Type="Table_Bida" IsForeignKey="true" />
    </Type>
  </Table>
</Database>